package com.liquilabs.vankoo.investor.core.designsystem

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

/**
 * Every semantic colour in the Vankoo design system, generated from the Figma
 * library.
 *
 * This exists alongside MaterialTheme.colorScheme rather than instead of it:
 * Material's scheme has fixed slots with no room for invoice status, risk
 * grade or the finance tokens, so those live here and the Material slots are
 * filled from this class in [VankooTheme].
 */
@Immutable
data class VankooColors(
    // Surfaces
    val surfaceBase: Color,
    val surfaceRaised: Color,
    val surfaceOverlay: Color,
    val surfaceSunken: Color,
    val surfaceInverse: Color,
    /** Anything that receives content: inputs, the amount field, a payment method row. */
    val surfaceField: Color,
    // Text
    val textPrimary: Color,
    val textSecondary: Color,
    val textMuted: Color, // 4.14:1 in light: only >=18sp or non-essential text
    val textDisabled: Color,
    val textInverse: Color,
    val textOnAction: Color, // sits on the brand green, never white
    val textLink: Color,
    val textSecondaryOnInverse: Color,
    // Borders
    val borderSubtle: Color,
    val borderDefault: Color,
    val borderStrong: Color, // inputs need 3:1
    val borderFocus: Color,
    // Actions
    val actionPrimaryBg: Color,
    val actionPrimaryBgHover: Color,
    val actionPrimaryBgActive: Color,
    val actionPrimaryFg: Color,
    val actionSecondaryBg: Color,
    val actionSecondaryBgHover: Color,
    val actionSecondaryBgActive: Color,
    val actionSecondaryFg: Color,
    val actionGhostBg: Color,
    val actionGhostBgHover: Color,
    val actionGhostFg: Color,
    val actionDangerBg: Color,
    val actionDangerBgHover: Color,
    val actionDangerFg: Color,
    val actionDisabledBg: Color,
    val actionDisabledFg: Color,
    // States
    val stateSuccessFg: Color,
    val stateSuccessBg: Color,
    val stateSuccessBorder: Color,
    val stateWarningFg: Color,
    val stateWarningBg: Color,
    val stateWarningBorder: Color,
    val stateErrorFg: Color,
    val stateErrorBg: Color,
    val stateErrorBorder: Color,
    // Money. Deliberately separate from state: cash flow is not a status.
    val financePositiveFg: Color,
    val financeNegativeFg: Color,
    val financeNeutralFg: Color,
    val financePositiveOnInverse: Color, // on an inverted surface the normal token drops to 2.92:1
    val financeNegativeOnInverse: Color,
    val financeNeutralOnInverse: Color,
    // Risk grade: one scoring system, not three.
    val riskAFg: Color,
    val riskABg: Color,
    val riskBFg: Color,
    val riskBBg: Color,
    val riskCFg: Color,
    val riskCBg: Color,
    // Accents
    val accentAiFg: Color, // also absorbs the role of "info": one blue, not two
    val accentAiBg: Color,
    val accentAiBorder: Color,
    val accentGreenFinanceFg: Color,
    val accentGreenFinanceBg: Color,
    val avatarBg: Color,
    val avatarFg: Color,
    // Decoration for fixed-brand surfaces. The panel is navy in BOTH modes, like
    // the Logo, so only decorDot flips; it is the one that sits on surfaceBase.
    // A fixed surface needs a fixed foreground: using textInverse here drops to
    // 1.92:1 in dark. Opacity is not a token — keep the green under 20%.
    val decorPanelFrom: Color,
    val decorPanelTo: Color,
    val decorPanelFg: Color,
    /** Labels on the panel. Fixed like the panel itself; not a palette step. */
    val decorPanelFgMuted: Color,
    /** A gain on the panel. finance/positive drops to 2.92:1 there, so this is its own value. */
    val decorPanelFgPositive: Color,
    val decorLightPrimary: Color,
    val decorLightSecondary: Color,
    val decorDot: Color,
    // Chart series, in the order the web assigns them.
    val chart1: Color,
    val chart2: Color,
    val chart3: Color,
    val chart4: Color,
    val chart5: Color,
    // Invoice status: the eleven values of InvoiceStatus in the Invoicing service.
    val statusUploadedFg: Color,
    val statusUploadedBg: Color,
    val statusOcrProcessingFg: Color,
    val statusOcrProcessingBg: Color,
    val statusDataExtractedFg: Color,
    val statusDataExtractedBg: Color,
    val statusConsistencyPassedFg: Color,
    val statusConsistencyPassedBg: Color,
    val statusSunatValidatingFg: Color,
    val statusSunatValidatingBg: Color,
    val statusSunatValidatedFg: Color,
    val statusSunatValidatedBg: Color,
    val statusApprovedFg: Color,
    val statusApprovedBg: Color,
    val statusPublishedFg: Color,
    val statusPublishedBg: Color,
    val statusRequiresReviewFg: Color,
    val statusRequiresReviewBg: Color,
    val statusNotEligibleFg: Color,
    val statusNotEligibleBg: Color,
    val statusRejectedFg: Color,
    val statusRejectedBg: Color,
)

internal val vankooLightColors = VankooColors(
    // Surfaces
    surfaceBase = VankooPalette.gray50,
    surfaceRaised = VankooPalette.white,
    surfaceOverlay = VankooPalette.white,
    surfaceSunken = VankooPalette.gray100,
    surfaceInverse = VankooPalette.navy900,
    surfaceField = VankooPalette.gray50,
    // Text
    textPrimary = VankooPalette.navy900,
    textSecondary = VankooPalette.gray700,
    textMuted = VankooPalette.gray600,
    textDisabled = VankooPalette.gray400,
    textInverse = VankooPalette.white,
    textOnAction = VankooPalette.navy900,
    textLink = VankooPalette.green700,
    textSecondaryOnInverse = VankooPalette.navy300,
    // Borders
    borderSubtle = VankooPalette.gray200,
    borderDefault = VankooPalette.gray300,
    borderStrong = VankooPalette.gray600,
    borderFocus = VankooPalette.green600,
    // Actions
    actionPrimaryBg = VankooPalette.green400,
    actionPrimaryBgHover = VankooPalette.green500,
    actionPrimaryBgActive = VankooPalette.green600,
    actionPrimaryFg = VankooPalette.navy900,
    actionSecondaryBg = VankooPalette.navy900,
    actionSecondaryBgHover = VankooPalette.navy800,
    actionSecondaryBgActive = VankooPalette.navy700,
    actionSecondaryFg = VankooPalette.white,
    actionGhostBg = VankooPalette.transparent,
    actionGhostBgHover = VankooPalette.gray100,
    actionGhostFg = VankooPalette.navy900,
    actionDangerBg = VankooPalette.red600,
    actionDangerBgHover = VankooPalette.red700,
    actionDangerFg = VankooPalette.white,
    actionDisabledBg = VankooPalette.gray200,
    actionDisabledFg = VankooPalette.gray400,
    // States
    stateSuccessFg = VankooPalette.green700,
    stateSuccessBg = VankooPalette.green50,
    stateSuccessBorder = VankooPalette.green300,
    stateWarningFg = VankooPalette.amber700,
    stateWarningBg = VankooPalette.amber50,
    stateWarningBorder = VankooPalette.amber300,
    stateErrorFg = VankooPalette.red700,
    stateErrorBg = VankooPalette.red50,
    stateErrorBorder = VankooPalette.red300,
    // Money. Deliberately separate from state: cash flow is not a status.
    financePositiveFg = VankooPalette.green700,
    financeNegativeFg = VankooPalette.red700,
    financeNeutralFg = VankooPalette.gray700,
    financePositiveOnInverse = VankooPalette.green300,
    financeNegativeOnInverse = VankooPalette.red300,
    financeNeutralOnInverse = VankooPalette.gray300,
    // Risk grade: one scoring system, not three.
    riskAFg = VankooPalette.green700,
    riskABg = VankooPalette.green50,
    riskBFg = VankooPalette.amber700,
    riskBBg = VankooPalette.amber50,
    riskCFg = VankooPalette.red700,
    riskCBg = VankooPalette.red50,
    // Accents
    accentAiFg = VankooPalette.indigo700,
    accentAiBg = VankooPalette.indigo50,
    accentAiBorder = VankooPalette.indigo200,
    accentGreenFinanceFg = VankooPalette.green800,
    accentGreenFinanceBg = VankooPalette.green100,
    avatarBg = VankooPalette.navy100,
    avatarFg = VankooPalette.navy700,
    decorPanelFrom = VankooPalette.navy800,
    decorPanelTo = VankooPalette.navy950,
    decorPanelFg = VankooPalette.white,
    decorPanelFgMuted = VankooPalette.panelFgMuted,
    decorPanelFgPositive = VankooPalette.panelFgPositive,
    decorLightPrimary = VankooPalette.green400,
    decorLightSecondary = VankooPalette.green500,
    decorDot = VankooPalette.gray300,
    chart1 = VankooPalette.green400,
    chart2 = VankooPalette.indigo600,
    chart3 = VankooPalette.amber400,
    chart4 = VankooPalette.navy600,
    chart5 = VankooPalette.red500,
    // Invoice status: the eleven values of InvoiceStatus in the Invoicing service.
    statusUploadedFg = VankooPalette.gray700,
    statusUploadedBg = VankooPalette.gray100,
    statusOcrProcessingFg = VankooPalette.indigo700,
    statusOcrProcessingBg = VankooPalette.indigo50,
    statusDataExtractedFg = VankooPalette.navy700,
    statusDataExtractedBg = VankooPalette.navy100,
    statusConsistencyPassedFg = VankooPalette.navy700,
    statusConsistencyPassedBg = VankooPalette.navy100,
    statusSunatValidatingFg = VankooPalette.indigo700,
    statusSunatValidatingBg = VankooPalette.indigo50,
    statusSunatValidatedFg = VankooPalette.navy700,
    statusSunatValidatedBg = VankooPalette.navy100,
    statusApprovedFg = VankooPalette.green700,
    statusApprovedBg = VankooPalette.green50,
    statusPublishedFg = VankooPalette.green800,
    statusPublishedBg = VankooPalette.green100,
    statusRequiresReviewFg = VankooPalette.amber700,
    statusRequiresReviewBg = VankooPalette.amber50,
    statusNotEligibleFg = VankooPalette.gray900,
    statusNotEligibleBg = VankooPalette.gray200,
    statusRejectedFg = VankooPalette.red700,
    statusRejectedBg = VankooPalette.red50,
)

internal val vankooDarkColors = VankooColors(
    // Surfaces
    surfaceBase = VankooPalette.navy950,
    surfaceRaised = VankooPalette.navy900,
    surfaceOverlay = VankooPalette.navy900,
    surfaceSunken = VankooPalette.navy950,
    surfaceInverse = VankooPalette.white,
    surfaceField = VankooPalette.navy950,
    // Text
    textPrimary = VankooPalette.gray100,
    textSecondary = VankooPalette.gray300,
    textMuted = VankooPalette.gray400,
    textDisabled = VankooPalette.gray700,
    textInverse = VankooPalette.navy950,
    textOnAction = VankooPalette.navy950,
    textLink = VankooPalette.green300,
    textSecondaryOnInverse = VankooPalette.gray700,
    // Borders
    borderSubtle = VankooPalette.navy800,
    borderDefault = VankooPalette.gray800,
    borderStrong = VankooPalette.gray600,
    borderFocus = VankooPalette.green400,
    // Actions
    actionPrimaryBg = VankooPalette.green400,
    actionPrimaryBgHover = VankooPalette.green300,
    actionPrimaryBgActive = VankooPalette.green500,
    actionPrimaryFg = VankooPalette.navy950,
    actionSecondaryBg = VankooPalette.navy700,
    actionSecondaryBgHover = VankooPalette.navy600,
    actionSecondaryBgActive = VankooPalette.navy600,
    actionSecondaryFg = VankooPalette.gray100,
    actionGhostBg = VankooPalette.transparent,
    actionGhostBgHover = VankooPalette.navy800,
    actionGhostFg = VankooPalette.gray100,
    actionDangerBg = VankooPalette.red600,
    actionDangerBgHover = VankooPalette.red500,
    actionDangerFg = VankooPalette.white,
    actionDisabledBg = VankooPalette.gray900,
    actionDisabledFg = VankooPalette.gray700,
    // States
    stateSuccessFg = VankooPalette.green300,
    stateSuccessBg = VankooPalette.green900,
    stateSuccessBorder = VankooPalette.green700,
    stateWarningFg = VankooPalette.amber300,
    stateWarningBg = VankooPalette.amber900,
    stateWarningBorder = VankooPalette.amber700,
    stateErrorFg = VankooPalette.red300,
    stateErrorBg = VankooPalette.red900,
    stateErrorBorder = VankooPalette.red700,
    // Money. Deliberately separate from state: cash flow is not a status.
    financePositiveFg = VankooPalette.green300,
    financeNegativeFg = VankooPalette.red300,
    financeNeutralFg = VankooPalette.gray300,
    financePositiveOnInverse = VankooPalette.green700,
    financeNegativeOnInverse = VankooPalette.red700,
    financeNeutralOnInverse = VankooPalette.gray700,
    // Risk grade: one scoring system, not three.
    riskAFg = VankooPalette.green300,
    riskABg = VankooPalette.green900,
    riskBFg = VankooPalette.amber300,
    riskBBg = VankooPalette.amber900,
    riskCFg = VankooPalette.red300,
    riskCBg = VankooPalette.red900,
    // Accents
    accentAiFg = VankooPalette.indigo300,
    accentAiBg = VankooPalette.indigo900,
    accentAiBorder = VankooPalette.indigo700,
    accentGreenFinanceFg = VankooPalette.green200,
    accentGreenFinanceBg = VankooPalette.green900,
    avatarBg = VankooPalette.navy800,
    avatarFg = VankooPalette.navy200,
    decorPanelFrom = VankooPalette.navy800,
    decorPanelTo = VankooPalette.navy950,
    decorPanelFg = VankooPalette.white,
    decorPanelFgMuted = VankooPalette.panelFgMuted,
    decorPanelFgPositive = VankooPalette.panelFgPositive,
    decorLightPrimary = VankooPalette.green400,
    decorLightSecondary = VankooPalette.green500,
    decorDot = VankooPalette.navy800,
    chart1 = VankooPalette.green400,
    chart2 = VankooPalette.indigo600,
    chart3 = VankooPalette.amber400,
    chart4 = VankooPalette.navy600,
    chart5 = VankooPalette.red500,
    // Invoice status: the eleven values of InvoiceStatus in the Invoicing service.
    statusUploadedFg = VankooPalette.gray300,
    statusUploadedBg = VankooPalette.gray900,
    statusOcrProcessingFg = VankooPalette.indigo300,
    statusOcrProcessingBg = VankooPalette.indigo900,
    statusDataExtractedFg = VankooPalette.navy300,
    statusDataExtractedBg = VankooPalette.navy800,
    statusConsistencyPassedFg = VankooPalette.navy300,
    statusConsistencyPassedBg = VankooPalette.navy800,
    statusSunatValidatingFg = VankooPalette.indigo300,
    statusSunatValidatingBg = VankooPalette.indigo900,
    statusSunatValidatedFg = VankooPalette.navy300,
    statusSunatValidatedBg = VankooPalette.navy800,
    statusApprovedFg = VankooPalette.green300,
    statusApprovedBg = VankooPalette.green900,
    statusPublishedFg = VankooPalette.green200,
    statusPublishedBg = VankooPalette.green900,
    statusRequiresReviewFg = VankooPalette.amber300,
    statusRequiresReviewBg = VankooPalette.amber900,
    statusNotEligibleFg = VankooPalette.gray400,
    statusNotEligibleBg = VankooPalette.gray900,
    statusRejectedFg = VankooPalette.red300,
    statusRejectedBg = VankooPalette.red900,
)
